server:
  port: 8080

spring:
  application:
    name: blog
  cloud:
    config:
      enabled: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: anselmo228
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
